before_install:
  - gem install puppet-lint>=1.0.1
#  - sudo apt-get install shellcheck
script:
# quite old puppet available in travis machines... It's a pitty...
#  - ./inception.sh
# shellcheck not available yet
#  - shellcheck inception.sh || true
  - puppet-lint templates/manifests
  - puppet-lint templates/profiles